/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletsIndexRouteImport } from './routes/wallets/index'
import { Route as MarketsIndexRouteImport } from './routes/markets/index'
import { Route as WalletsWalletIdRouteImport } from './routes/wallets/$walletId'
import { Route as MarketsMarketIdRouteImport } from './routes/markets/$marketId'
import { Route as ApiHealthRouteImport } from './routes/api/health'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsIndexRoute = WalletsIndexRouteImport.update({
  id: '/wallets/',
  path: '/wallets/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/markets/',
  path: '/markets/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletsWalletIdRoute = WalletsWalletIdRouteImport.update({
  id: '/wallets/$walletId',
  path: '/wallets/$walletId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsMarketIdRoute = MarketsMarketIdRouteImport.update({
  id: '/markets/$marketId',
  path: '/markets/$marketId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/wallets/$walletId': typeof WalletsWalletIdRoute
  '/markets/': typeof MarketsIndexRoute
  '/wallets/': typeof WalletsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/wallets/$walletId': typeof WalletsWalletIdRoute
  '/markets': typeof MarketsIndexRoute
  '/wallets': typeof WalletsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/markets/$marketId': typeof MarketsMarketIdRoute
  '/wallets/$walletId': typeof WalletsWalletIdRoute
  '/markets/': typeof MarketsIndexRoute
  '/wallets/': typeof WalletsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/api/health'
    | '/markets/$marketId'
    | '/wallets/$walletId'
    | '/markets/'
    | '/wallets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/api/health'
    | '/markets/$marketId'
    | '/wallets/$walletId'
    | '/markets'
    | '/wallets'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/api/health'
    | '/markets/$marketId'
    | '/wallets/$walletId'
    | '/markets/'
    | '/wallets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  ApiHealthRoute: typeof ApiHealthRoute
  MarketsMarketIdRoute: typeof MarketsMarketIdRoute
  WalletsWalletIdRoute: typeof WalletsWalletIdRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
  WalletsIndexRoute: typeof WalletsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets/': {
      id: '/wallets/'
      path: '/wallets'
      fullPath: '/wallets/'
      preLoaderRoute: typeof WalletsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/markets'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallets/$walletId': {
      id: '/wallets/$walletId'
      path: '/wallets/$walletId'
      fullPath: '/wallets/$walletId'
      preLoaderRoute: typeof WalletsWalletIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$marketId': {
      id: '/markets/$marketId'
      path: '/markets/$marketId'
      fullPath: '/markets/$marketId'
      preLoaderRoute: typeof MarketsMarketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  ApiHealthRoute: ApiHealthRoute,
  MarketsMarketIdRoute: MarketsMarketIdRoute,
  WalletsWalletIdRoute: WalletsWalletIdRoute,
  MarketsIndexRoute: MarketsIndexRoute,
  WalletsIndexRoute: WalletsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
